# Generated by Django 5.0.2 on 2024-02-19 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodApp', '0002_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='hopitalid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BloodApp.hospital'),
        ),
    ]
