# Generated by Django 5.0.2 on 2024-02-19 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BloodApp', '0004_appointments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='hopitalid',
            new_name='hospitalid',
        ),
    ]
